PullRequest Dara
Skalas/Matematicas-Computacionales-fall2021 pull request #12
Opened 2021-08-19 01:04 UTC by DaraMeneses

Wuuu gracias

2021-09-06 00:03 UTC, DaraMeneses commented
Se verificó que en "files change" se encuentran los archivos project_euler1 y project_euler2

2021-10-04 03:44 UTC, DaraMeneses commented
Se entregó la primera Tarea :))

2021-10-05 03:49 UTC, DaraMeneses commented
Ahora sí, se entregó bien la primera Tarea :D

2021-10-07 06:12 UTC, Skalas requested changes
Hay muchos cambios a los archivos de la clase! por favor arréglalos 💯 
![image](https://user-images.githubusercontent.com/5437081/136329359-23c22b4c-e6dc-4641-8def-1f9e443786b3.png)

2021-10-12 01:33 UTC, merged